### ISSUE TITLE
sign in => sign up?

### ISSUE THREAD

**Issue by j2l** [joshnuss/supabase-sveltekit-example#3]
Hello again, 
Using the example:
![image](https://user-images.githubusercontent.com/65325/117938939-db47f080-b307-11eb-86b0-b4903f092423.png)
I removed the email for the screenshot, it's a working one. And the password is correct.
And I click Sign In of course :)

sign-in.svelte is:
```
<script lang="ts">
  import Auth from 'supabase-ui-svelte'
  import { supabase } from '$lib/db'
</script>

<div class="container">
  <h1>Sign in</h1>

  <Auth supabaseClient={supabase} providers={['google', 'twitter']}/>
</div>

<style>
  .container {
    display: flex;
    flex-direction: column;
    width: 400px;
    margin: 0px auto;
  }
</style>
```

**Comment by joshnuss** [comment]
I think it's related to this: https://github.com/joshnuss/supabase-ui-svelte/pull/1

I pushed an NPM package update, and bumped the version in b126f02. Let me know if it fixes it for you.

Sorry about the rough edges, but thanks for reporting these issues!

**Comment by j2l** [comment]
Yes, bumping from 0.1.0 to 0.1.1 make it work.
There's just no redirect, might be useful to add it in this example project :)
Also, it needs a refresh to get the localstorage object, I don't know if there's a way to auto-refresh this page when coming from sign-in route.

Thank you very much for teaching me Svelte! :smile_cat:
